description: mnist_tf_const
data:
  validation_set_size: 10000
checkpoint_storage:
  type: s3
  access_key: AKIAJGK24F32WWJ25AEA
  secret_key: 08OM18juqj9p2ivz0kBkxsFVuY/yoC9A0fDHmSeA
  bucket: determined-ai-examples
hyperparameters:
  base_learning_rate: 0.001
  weight_cost: 0.0001
  batch_size: 64
  n_filters1: 40
  n_filters2: 40
searcher:
  name: single
  metric: error
  max_steps: 5
  smaller_is_better: true
environment:
  runtime_packages: ["tensorflow_datasets"]
